spring:
  application:
    name: user-service # must match the filename in config-repo exactly
  config:
    import: "configserver:http://config-server.eventsphere.internal:8888"
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server.eventsphere.internal:8761/eureka/
